# Generated by Django 4.0.1 on 2022-01-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_price_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Core', 'core'), ('Full', 'full'), ('Part Time', 'part-time')], default='Full', max_length=30),
        ),
    ]
