# Generated by Django 4.0.1 on 2022-01-28 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermembership',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
