# Generated by Django 4.0.1 on 2022-02-03 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0004_usermembership_stripe_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='stripe_customer_id',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
