# Generated by Django 4.0.1 on 2022-02-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_alter_stripedetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripedetails',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
