# Generated by Django 4.0.1 on 2022-02-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_alter_stripedetails_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripedetails',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
