# Generated by Django 4.0.1 on 2022-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(null=True, related_name='order_product', to='shop.Order'),
        ),
    ]
