# Generated by Django 4.0.1 on 2022-01-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_orders_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='packed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order_product', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.DateTimeField(null=True),
        ),
    ]
