# Generated by Django 4.0.1 on 2022-01-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_image_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
